### ISSUE TITLE
Searching tool box missing?

### ISSUE THREAD

**Issue by jcponce** [geogebra/manual#362]
Hello everyone!

First of all, thanks for updating the manual documentation. I really love this version, which is easier to navigate. 

I was wondering if you are going to add a **Searching tool box**. I saw in the Antora documentation, and they have one: https://docs.antora.org/antora/latest/ 

Are you considering to add it later?

Kind regards.

**Comment by zbynek** [comment]
We're looking into this. The default implementation creates a single index for all languages which is 
1) big (almost 5MB)
2) confusing (exact match from another language has higher priority than partial match from current one...)

**Comment by zbynek** [comment]
For now we added Google Search which avoids loading the huge index file and for language filtering it may be slightly smarter than the built-in search in Antora (https://github.com/geogebra/docs/commit/5c2846cd1e8f1630ea8e6c6b5bf9b28ed3de55d9). OTOH it doesn't support search-as-you-type, so we might give the built-in search another shot in the future.
